export const medicines = [
  {
    id: "dcd",
    title: "Napa 500mg",
    price: 5,
    totalStock: 100,
    brandName: "Square",
    rating: 4.6,
    sortDescription: "lorem ipsum dolor sit amet",
    longDescription: "lorem201 dolor sit amet",
    discountPrice: 4,
  },
  {
    id: "dcdcdcd",
    title: "Napa 500mg",
    price: 5,
    totalStock: 100,
    brandName: "Square",
    rating: 4.6,
    sortDescription: "lorem ipsum dolor sit amet",
    longDescription: "lorem201 dolor sit amet",
    discountPrice: 4,
  },
  {
    id: "cdcdc",
    title: "Napa 500mg",
    price: 5,
    totalStock: 100,
    brandName: "Square",
    rating: 4.6,
    sortDescription: "lorem ipsum dolor sit amet",
    longDescription: "lorem201 dolor sit amet",
    discountPrice: 4,
  },
];
