import { ContextProvider } from "@/provider/contextProvider";
import { Inter } from "next/font/google";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import SessionProvider from "../provider/sessionProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <ContextProvider>
          <SessionProvider>{children}</SessionProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
